package org.cmdbuild.workflow.event;

import org.cmdbuild.workflow.CMWorkflowException;

/**
 * Receives and processes workflow events.
 */
public interface WorkflowEventManager {

	/**
	 * Adds an event generated by a certain session.
	 * 
	 * @param sessionId
	 * @param event
	 */
	void pushEvent(int sessionId, WorkflowEvent event);

	/**
	 * Process events for a certain session and remove them.
	 * 
	 * @param sessionId
	 */
	void processEvents(int sessionId) throws CMWorkflowException;

	/**
	 * Remove events for a certain session without processing them.
	 * 
	 * @param sessionId
	 */
	void purgeEvents(int sessionId);
}
